# Site settings
title: UDW22
email: udw-organisers@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  Universal Dependencies Workshop 2022 (UDW'22)
baseurl: "/udw22" # the subpath of your site, e.g. /blog/
url: "http://universaldependencies.org" # the base hostname & protocol for your site
twitter_username: ud_workshop
# github_username:  jekyll

# Build settings
markdown: kramdown
